import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./src/renderer/index.html', './src/renderer/src/**/*.{vue,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#131315',
        surface: '#131315',
        'surface-dim': '#131315',
        'surface-bright': '#39393b',
        'surface-variant': '#353437',
        'surface-tint': '#00daf3',
        'surface-container-lowest': '#0e0e10',
        'surface-container-low': '#1b1b1d',
        'surface-container': '#1f1f21',
        'surface-container-high': '#2a2a2c',
        'surface-container-highest': '#353437',

        'on-background': '#e4e2e4',
        'on-surface': '#e4e2e4',
        'on-surface-variant': '#bac9cc',
        'inverse-surface': '#e4e2e4',
        'inverse-on-surface': '#303032',

        outline: '#849396',
        'outline-variant': '#3b494c',

        primary: '#c3f5ff',
        'on-primary': '#00363d',
        'primary-container': '#00e5ff',
        'on-primary-container': '#00626e',
        'inverse-primary': '#006875',
        'primary-fixed': '#9cf0ff',
        'primary-fixed-dim': '#00daf3',
        'on-primary-fixed': '#001f24',
        'on-primary-fixed-variant': '#004f58',

        secondary: '#c8c6c8',
        'on-secondary': '#303032',
        'secondary-container': '#474649',
        'on-secondary-container': '#b7b4b7',
        'secondary-fixed': '#e5e1e4',
        'secondary-fixed-dim': '#c8c6c8',
        'on-secondary-fixed': '#1b1b1d',
        'on-secondary-fixed-variant': '#474649',

        tertiary: '#ececec',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#d0d0d0',
        'on-tertiary-container': '#575959',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',

        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'element-gap': '0.75rem',
        'panel-margin': '1rem',
        'container-padding': '1.5rem',
        'max-width-chat': '320px',
      },
      fontFamily: {
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['Geist', 'monospace'],
        'mono-status': ['Geist', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'mono-status': ['12px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
} satisfies Config
